# Generated by Django 5.1.3 on 2024-12-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='student_id',
        ),
    ]
